---

kind: pipeline
name: default

steps:
- name: build  
  image: plugins/docker
  environment:
    username: 
      from_secret: DOCKER_HUB_USERNAME
    password: 
      from_secret: DOCKER_HUB_PASS
      repo: mattb912/pingbotmc
      tags: mattb912/pingbotmc:latest
      dockerfile: ./Dockerfile
