---
kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    username: 
      from_secret: DOCKER_HUB_USERNAME
    password: 
      from_secret: DOCKER_HUB_PASS
    repo: matt/pingbotmc
    tags: latest

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: SLACK_WEBHOOK
    channel: my-notifications

