---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: docker
  image: plugins/docker
  settings:
    password:
      from_secret: DOCKER_ACCESS_TOKEN
    repo: matt/pingbotmc
    tags: latest
    username:
      from_secret: DOCKER_HUB_USERNAME

- name: slack
  image: plugins/slack
  settings:
    channel: my-notifications
    webhook:
      from_secret: SLACK_WEBHOOK
    when:
      status:
      - success
      - failure

...