---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: plugins/docker
  settings:
    build_args_from_env:
    - MC_LOGIN
    - MC_PASS
    - TEST_URL
    - SLACK_WEBHOOK
    secrets:
    - MC_LOGIN
    - MC_PASS
    - TEST_URL
    - SLACK_WEBHOOK

    password:
      from_secret: docker_hub_password
    repo: mattb912/pingbotmc
    tags: latest
    username:
      from_secret: DOCKER_HUB_USERNAME

- name: notify
  image: plugins/slack-blame
  settings:
    channel: my-notifications
    failure_image_attachments:
    - https://i.imgur.com/wmuIsi1.jpg
    failure_template: "The build is broken! Blame {{slack.name}}\n"
    success_image_attachments:
    - http://i.imgur.com/TP4PIxc.jpg
    success_template: "The build is fixed! Thanks @{{slack.name}}\n"
    token:
      from_secret: drone_bot_auth_token
  when:
      status: 
      - success
      - failure


...